# Generated by Django 4.1.2 on 2022-10-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_book_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='book',
            field=models.ManyToManyField(blank=True, null=True, to='store.book'),
        ),
    ]
