# Generated by Django 4.1.2 on 2022-10-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_store_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Couponcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('use_count', models.IntegerField(max_length=100)),
                ('expiry', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='book_price',
            field=models.IntegerField(default=1),
        ),
    ]
