# Generated by Django 4.1.2 on 2022-10-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_couponcode_book_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcode',
            name='discount',
            field=models.IntegerField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
