# Generated by Django 4.1.2 on 2022-10-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_couponcode_discount_alter_couponcode_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='use_count',
            field=models.IntegerField(default=0),
        ),
    ]
